---
title: "DS6371 Kaggle Project"
author: "Christopher Dawson, Matt Farrow"
date: "8/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction 

### Data Description 
(Where did the data come from?  How big is it? How many observations?  Where can we find out more?  What are the specific variables that we need to know with respect to your analysis?)

## Analysis Question 1:

### Restatement of Problem 

### Build and Fit the Model
	 
### Checking Assumptions 
- Residual Plots 
- Influential point analysis (Cook’s D and Leverage)
- Make sure to address each assumption.

### Comparing Competing Models
- Adj R2  
- Internal CV Press  

### Parameters
- Estimates
- Interpretation 
- Confidence Intervals 

### Conclusion
	
## Analysis Question 2

### Restatement of Problem 

### Model Selection

Type of Selection
- Stepwise
- Forward
- Backward
- Custom 		 

### Checking Assumptions 

- Residual Plots
- Influential point analysis (Cook’s D and Leverage)
- Make sure to address each assumption

### Comparing Competing Models
- Adj R2   
- Internal CV Press   
- Kaggle Score 

### Conclusion: A short summary of the analysis.  

## Appendix

